### ISSUE TITLE
stdWindow - variable minStackSize is never assigned

### ISSUE THREAD

**Issue by 6DiegoDiego9** [sancarn/stdVBA#109]
In

```
Private Function stackPopV(ByRef stack() As tFindNode, ByRef index As Variant) As tFindNode
    Dim size As Long: size = UBound(stack) + 1
    If index < size / 3 And index > minStackSize Then
        ReDim Preserve stack(0 To CLng(size / 2))
    End If
```

... the variable minStackSize is never assigned.
Did you intend to assign 1 to it? or to make it an optional argument?

**Comment by sancarn** [comment]
Good question, the code was taken from `stdLambda` I think where `Private Const minStackSize as Long = 30` but I'm not 100% sure now what this even does... xD
