### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by mazzalorenzo** [sancarn/stdVBA#114]
stdImage and stdUIElements gives me compilation error with Rubberduck, while fullBuild.xlsm gives me error 1

**Comment by sancarn** [comment]
1. Not sure why RubberDuck would be reporting compilation errors, the regular VBE doesn't report any such errors. @retailcoder any idea why this might be?
2. `fullBuild.xlsm` does require access to VBOM - maybe this is the issue? Unsure though, I do not get such errors on my end.

![image](https://github.com/user-attachments/assets/3bdf7b09-fc73-415f-9f0e-e3dabc12f5e5)

**Comment by mazzalorenzo** [comment]
Thanks, that flag was surely part of the problem. However when i try to refresh in Rubberduck it continues to give me this prompt: 

<img src="https://github.com/user-attachments/assets/6c7d67d1-8768-40c5-82c6-9e1ed671ec06" alt="drawing" width="300"/>

**Comment by mazzalorenzo** [comment]
Using the built-in debug menu it points to the following function saying ```User defined type not defined```:
> Public Function ToSheet(ByVal ws As Worksheet, Optional ByVal top As Double = 0, Optional ByVal left As Double = 0, Optional ByVal compress As MsoPictureCompress) As Object
  Set ToSheet = ws.Shapes.AddPicture2(ToTempFile(), False, 0, top, left, -1, -1, compress)
End Function


Maybe the reason is somehow MsoPictureCompress

**Comment by mazzalorenzo** [comment]
I tried replacing MsoPictureCompress with object or long and it doesn't throw the error anymore. I'm on Excel 2010

**Comment by retailcoder** [comment]
Good stuff! Make sure the code isn't going to try to invoke Excel 2016+ features when it's running in Excel 2010, and then everything should be fine at run-time as well!
