### ISSUE TITLE
How to use fullBuild.xlam

### ISSUE THREAD

**Issue by mazzalorenzo** [sancarn/stdVBA#115]
Maybe due to my ignorance I can't manage to use any object in FullBuild.xlam when I add it as an addin. Is there somewhere a procedure I can follow to do it? Is it even possible?
Thank you

**Comment by sancarn** [comment]
Post-build you need to:

1. Ensure all objects are exposed
2. Reference the xlam in your vba project

Realistically, I wouldn't do it this way, though some people prefer it. I'm still awaiting a means to build this automatically on github which will at least make only step 2 required.
