### ISSUE TITLE
Parsing arithmetic operators in StdLambda

### ISSUE THREAD

**Issue by giulio-mae** [sancarn/stdVBA#32]
Hello, I probably found an issue in how StdLambda parses expressions involving * and / operators.
Consider the following: 
Set lambda = stdLambda.Create("$1 * $2 / $3 * $4")

If I evaluate lambda(1,2,2,2), the result is 0.5 instead of 2.

Thank you

**Comment by sancarn** [comment]
Can confirm the bug, thanks :)

**Comment by sancarn** [comment]
Reviewed with Tar. Tar noticed that `parseArithmeticPriority4` should be calling `parseArithmeticPriority5` rather than 4. Ultimately this was a typo. Thanks for reporting the issue!

**Comment by giulio-mae** [comment]
Hi, I recently updated the library to the newest version and I think this bug has reappeared...
Set lambda = stdLambda.Create("$1 / $2 / $3")
lambda(2, 2, 2)  is again evaluated as 2

**Comment by sancarn** [comment]
@giulio-mae Thanks, not sure how this snuck back in again... But fixed again now 👍
