### ISSUE TITLE
Unable to push vbObject into Array

### ISSUE THREAD

**Issue by SZanko** [sancarn/stdVBA#46]
# Description

Currently if a class is pushed to a stdArray it throws a runtime error

# Expected Result

The stdArray should work as the javascript array without throwing an error

# Example

```vba
Dim myClass as new MyClassModule
Dim arr as new stdArray
Set arr = stdArray.create()

arr.push(myClass)
```
## Error

Runtime error:  438

Object does not support this property or method

# Workaround

My Current Workaround for this problem is that I convert the vbObject to a vbVariant

**Comment by sancarn** [comment]
Hi there @SZanko this is an error on your behalf:

```vb
arr.push (...)
```

is incorrect syntax, this is equivalent of evaluating the default property of `MyClassModule`, which I suppose you haven't provided, which is why you are getting the error. Instead use correct VBA syntax:

```vb
arr.push myClass
```

or

```vb
Call arr.push(myClass)
```
