### ISSUE TITLE
Fix `stdProcess` structure issue with ProcessEntry32

### ISSUE THREAD

**Issue by sancarn** [sancarn/stdVBA#59]
See this issue for quotation:

https://github.com/twinbasic/twinbasic/issues/1031#issuecomment-1196277353

Ultimately `pcPriClassBase` should be a `Single` not a `Long` type

```
Private Type PROCESSENTRY32
    dwSize As Long
    cntUsage As Long
    th32ProcessID As Long
    'pack1 As Long
    th32DefaultHeapID As LongPtr
    th32ModuleID As Long
    cntThreads As Long
    th32ParentProcessID As Long
    pcPriClassBase As Single         'Bugfix
    dwFlags As Long
    szExeFile As String * 260
    'pack2 As Long
End Type

```

**Comment by sancarn** [comment]
I appear to have misunderstood what FAFALONE was indicating, it is correct that ClassName should be a long, not a single. Instead fafalone indicated the examples they'd found in VBA had padded pcPriClassBase with a long e.g.

```
  pcPriClassName as long
  padding as long
  ...
```

This likely came about because people know MAX_PATH is actually 256, however the MAX_PATH constant = 260. So an extra 4 bytes were added about the place.

**Comment by fafalone** [comment]
While it doesn't error because a Single is a 4-byte data type, [officially it's a Long](https://learn.microsoft.com/en-us/windows/win32/api/tlhelp32/ns-tlhelp32-processentry32),

```
typedef struct tagPROCESSENTRY32 {
  DWORD     dwSize;
  DWORD     cntUsage;
  DWORD     th32ProcessID;
  ULONG_PTR th32DefaultHeapID;
  DWORD     th32ModuleID;
  DWORD     cntThreads;
  DWORD     th32ParentProcessID;
  LONG      pcPriClassBase;
  DWORD     dwFlags;
  CHAR      szExeFile[MAX_PATH];
} PROCESSENTRY32;
```

and it will have one of the following values,

```
    NORMAL_PRIORITY_CLASS = &H20
    IDLE_PRIORITY_CLASS = &H40
    HIGH_PRIORITY_CLASS = &H80
    REALTIME_PRIORITY_CLASS = &H100
    BELOW_NORMAL_PRIORITY_CLASS = &H4000
    ABOVE_NORMAL_PRIORITY_CLASS = &H8000
```

never a decimal.

**Comment by sancarn** [comment]
Thanks, I had initially used long as I usually go direct from the structs anyhow, but saw the issue in your vbforums post, so figured I might have got it wrong also 😅

Thanks for the increased information! 👍

**Comment by fafalone** [comment]
No problem, I obviously got it wrong a few times too. 

But yeah a Single will result in lots of trouble if you ever did anything with the data WIndows copies in thinking it's a Long. :)
