### ISSUE TITLE
FullBuild.xlam disaligned with srcWindow.cls

### ISSUE THREAD

**Issue by 6DiegoDiego9** [sancarn/stdVBA#65]
In FullBuild.xlam I get an error on the line "RectClient = rect" because RectClient is read-only (true, since it has no letter proc.)

```
Public Property Let RectByType(Optional iClWnd As EWndRectType, ByVal rect As Variant)
  Select Case iClWnd
    Case EWndRectType.RectTypeClient
      RectClient = rect
    Case EWndRectType.RectTypeWindow
      RectWindow = rect
  End Select
End Property
```

However, src\stdWindow.cls has "RectWindow = rect" in its place.

I'm new to your repository.  Should I always take the src files as the latest version?

**Comment by sancarn** [comment]
> because RectClient is read-only (true, since it has no letter proc.)

Ah yes, sorry, forgot about that. Yeah I could never find out how the client was calculated compared to the window so never quite figured out how to resize based on client... It's a WIP feature that I guess I forgot to complete... Thanks for posting. You should at least be able to use `iClWnd = RectTypeWindow`? Or does it error irrespectively?

**Comment by 6DiegoDiego9** [comment]
I see, however even after I replaced all the classes of FullBuild.xlam with the src\*.cls, I still get errors:

![image](https://user-images.githubusercontent.com/109476941/215545772-eb9baa75-d9c4-4cce-bb17-ae8d58773dd3.png)

![image](https://user-images.githubusercontent.com/109476941/215545847-e1da8864-b5d6-447c-ae8b-0c7d5f2b8238.png)


I corrected(?) by removing the parenthesis and adding an "s".

**Comment by sancarn** [comment]
Sorry, what are you trying to do, is there a reason you need all modules to be compile error free from the get go?

**Comment by 6DiegoDiego9** [comment]
Thanks for the fixes 👍 
I'm just giving a look at everything for the first time, to evaluate hands-on what to keep and discard.
What if I'll want to contribute with some work on some selected libraries? if you work on them offline for days, it would be risky...

**Comment by sancarn** [comment]
> if you work on them offline for days, it would be risky

Whenever I make a change usually I commit straight away, although sometimes features are in planning for a while. Git sorts most of the conflicts out and I will likely have to help you through your first Pull Request, but that's fine and something I'm happy to do so long as it fits in with the strategy of the project :). Might be worth raising an issue with any ideas you want to implement first or taking something from the [existing roadmap](https://github.com/sancarn/stdVBA/projects/1) if any peak your fancy :) 

> What if I'll want to contribute with some work on some selected libraries

If you do want to make a change or an addition:
1. Make a branch of the repository.
2. Make any changes / additions you want to make to your own branch.
3. Create a "Pull Request"
4. We'll resolve any conflicts together
5. And if all goes well I'll approve it into the library.

If you have any specific

**Comment by sancarn** [comment]
Closing this as issues fixed
