### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by alexofrhodes** [sancarn/stdVBA#75]
Trojan detected in \sancarn\stdVBA-examples\Examples\Spreadsheet Extractor\ExtractionTemplate 1.1.xlsm

![Screenshot - 02-Jun-23 , 9_02_28 AM](https://github.com/sancarn/stdVBA/assets/62287665/6699ae97-73b5-4722-b14d-8b20d6ac71f8)

**Comment by sancarn** [comment]
False positive, definitely not a trojan (you can check the code for yourself), but I'm not sure what can be done to rectify the situation unfortunately. You can re-build it from source if needed.... Though that's still quite difficult. I might be able to make that easier though...

**Comment by sancarn** [comment]
I've reported it to Microsoft on [this](https://www.microsoft.com/en-us/wdsi/filesubmission/) link. I also raised it with [VirusTotal](https://www.virustotal.com/gui/file/98e2bfe4c141c6eebee2b4fed1ea11ad0f89b33d8a44e0051adb1881391a019f/detection). 

Unfortunately "12 security vendors and 1 sandbox flagged this file as malicious"... Not sure how to resolve this...

**Comment by sancarn** [comment]
Next steps:

Replace powershell commands from stdCOM

**Comment by sancarn** [comment]
Removed this code for now, will figure out a workaround later.
