### ISSUE TITLE
VB6 vs VBA classes

### ISSUE THREAD

**Issue by DecimalTurn** [sancarn/stdVBA#78]
There is currently about 20% of the code detected as VB6.

![image](https://github.com/sancarn/stdVBA/assets/31558169/1ee7f062-4dbe-4d0f-8489-9934d61690a9)

That is because these 5 classes have the `Persistable` metadata key at the top of the file[^1]:

* https://github.com/sancarn/stdVBA/blob/bc4dd5cb407dc5ebfab9bf825ec9d8763a6e2e06/src/WIP/stdObject.cls#L4
* https://github.com/sancarn/stdVBA/blob/bc4dd5cb407dc5ebfab9bf825ec9d8763a6e2e06/src/WIP/IFauxInterface.cls#L4
* https://github.com/sancarn/stdVBA/blob/bc4dd5cb407dc5ebfab9bf825ec9d8763a6e2e06/src/WIP/STD_Automation_DLL.cls#L4
* https://github.com/sancarn/stdVBA/blob/bc4dd5cb407dc5ebfab9bf825ec9d8763a6e2e06/src/WIP/ideas/cUniversalDLLCalls.cls#L4
* https://github.com/sancarn/stdVBA/blob/bc4dd5cb407dc5ebfab9bf825ec9d8763a6e2e06/src/WIP/stdJSON/JSONBag%20Licensed/JsonBag%202.0/JsonBag.cls#L4

Normally, for VBA classes, this metadata is absent and we simply have:

```vba
BEGIN
  MultiUse = -1  'True
END
```

I'd suggest to standardize the metadata section accross all classes since the extra metadata is ignored by VBA anyway.

[^1]: This detection rule comes from this regex in github-linguist: https://github.com/github-linguist/linguist/blob/7ca3799b8b5f1acde1dd7a8dfb7ae849d3dfb4cd/lib/linguist/heuristics.yml#L156C7-L156C7

**Comment by sancarn** [comment]
Thanks @DecimalTurn for another great issue. Agreed.

Many of the above classes are likely in need of removal also as they are mostly legacy ideas which are just copies of existing classes from VB6 at present. Unsure if they are adding unnecessary clutter.

**Comment by sancarn** [comment]
Looking now [it is mostly bas modules](https://github.com/search?q=repo%3Asancarn%2FstdVBA++language%3A%22Visual+Basic+6.0%22&type=code) not sure if there is a method to get these to show up properly?

**Comment by DecimalTurn** [comment]
@sancarn There is a way if you want to make it all VBA. For modules, there are a [few regexes ](https://github.com/github-linguist/linguist/blob/7ca3799b8b5f1acde1dd7a8dfb7ae849d3dfb4cd/lib/linguist/heuristics.yml#L868) that can make the file detected as VBA but the easiest is to have simply "VBA" appear somewhere in the code. Hence, a simple comment at the top like this would be enough:

```vba
'Lang: VBA
```
