### ISSUE TITLE
Compatible Long And Longptr

### ISSUE THREAD

**Issue by SanbiVN** [sancarn/stdVBA#81]
hi Pro!

This declaration code is not compatible with Win64 OS and Office 32bit,
causing code compilation error: "Compile error: Expected: identifier"

![1680054150970](https://github.com/sancarn/stdVBA/assets/58664571/0590c2e4-56ab-4ebd-955c-4e54e072f571)

```
#If VBA7 Then
#Else
Private Enum LongPtr
      [_]
End Enum
#End If
```

--------------------------------------------------

This code works on Win64 and Office 32bit, I have verified
```
#If VBA7 = 0 Then
   'Private Enum LongLong:[_]:End Enum ' This declaration is required
   #If VBA6 = 0 OR Win64 = 0 Then
   Private Enum LongPtr:[_]:End Enum
   #End If
#End If
```

Thanks for your Project!

**Comment by sancarn** [comment]
Hello,

Which file did you find this declaration in? I don't actually see it anywhere...

**Comment by sancarn** [comment]
> So I'm not sure why this would be throwing a compile error

It could be a corrupt VBA module. I'd suggest commenting out the module, saving it, and uncommenting the module again. This will reset the structure of the pcode and ensure it isn't a corruption issue.

**Comment by SanbiVN** [comment]
Hi @sancarn!

Bạn hãy đọc cuộc trò chuyện giữa tôi và @cristianbuse, có thể bạn sẽ hiểu thêm vấn đề.

https://github.com/cristianbuse/VBA-UserForm-MouseScroll/issues/30

**Comment by sancarn** [comment]
As discussed in  https://github.com/cristianbuse/VBA-UserForm-MouseScroll/issues/30 won't fix this as it's unexpected and will affect compatibility with VB6

**Comment by cristianbuse** [comment]
Hi @SanbiVN ,

The declaration you proposed is not compatible as you might think. I understand that some of your users already have ```LongPtr``` for VBA6 but when I test on my computers, I do not have ```LongPtr``` in VBA6. So, I still need the enum declaration. In other words, the declaration used in this repo and in mine work but yours does not work.

**Comment by sancarn** [comment]
You are unlikely to be able to get around it, unless you can determine at compile time whether `LongPtr` is defined or not. One option would be:

```vb
#If VBA7 = 0 and isLongPtrDefinedx32 = 0 Then
   Private Enum LongPtr:[_]:End Enum
#End If
```

Then you can apply a patch to the compiler args of customer's projects, perhaps.

**Comment by sancarn** [comment]
> ```vba
> #If VBA7 = 0 And Win64 = 0 Then
>    Private Enum LongPtr:[_]:End Enum
> #End If

Does this resolution work for your users? Seems weird to me that `Win64` is `true` for them.

**Comment by sancarn** [comment]
```vb
#If Win64 = 0 Then
```

is different to

```vb
#If VBA7 = 0 Then
```

If that's what you are asking. 

---

I think cristian is saying is that adding the `Win64` declaration to this:

```vb
#If VBA7 = 0  And Win64 = 0 Then
```

**Should** cause no difference, because you only have Win64 under VBA7. 

---

It would be really useful if your users could actually run the code previously suggested by cristian:

```vb
Sub TestPreCompilerConstants()
    Dim m As String
    Dim b As String
    Dim v As String
    '
    #If Mac Then
        m = "Mac"
    #Else
        m = "Windows"
    #End If
    '
    #If Win64 Then
        b = "x64"
    #Else
        b = "x32"
    #End If
    '
    #If VBA7 Then
        v = "VBA7"
    #Else
        v = "VBA6 (or prior)"
    #End If
    '
    MsgBox "You are on " & m & " OS, on " & b & " Office, on " & v
End Sub
```

And report back on what the msgbox says. I did see [your thread](https://www.giaiphapexcel.com/diendan/threads/vba-n%C3%A2ng-cao-winapi-khai-b%C3%A1o-long-v%C3%A0-longptr-t%C6%B0%C6%A1ng-th%C3%ADch-%C4%91a-n%E1%BB%81n-t%E1%BA%A3ng.164609/) but can't read vietnamese so am only getting what google gives me 😂 But I can see that your users haven't ran this specific code snippet. It would be very helpful if they did, as then we really can see if we can build anything robust or not.

**Comment by sancarn** [comment]
How bizarre that case2 where `Win64` is included has any effect when supposedly the msgbox claimed that they were on VBA7 and 32 bit O_o Thanks for the info, I'll change the declares in stdVBA, it can't hurt at least...

**Comment by cristianbuse** [comment]
Hi @SanbiVN ,

Thanks. Out of curiosity, does this work for your users?
```VBA
#If VBA7 = 0 And True Then
   Private Enum LongPtr:[_]:End Enum
#End If
```
Or this?
```VBA
#If True And VBA7 = 0 Then
   Private Enum LongPtr:[_]:End Enum
#End If
```

There is [this](https://stackoverflow.com/a/65259128/8488913) compiler bug that I know. Since that post the bug was only partially fixed.

**Comment by cristianbuse** [comment]
@SanbiVN ,

I know, but so ```Win64 = 0``` is always ```True``` when ```VBA7 = 0``` and yet you are saying that some users experience compiler errors. So, I was just curious if repalcing with ```True``` directly still works. Please indulge me 😄

**Comment by cristianbuse** [comment]
@SanbiVN ,

So, can your users test the [two cases](https://github.com/sancarn/stdVBA/issues/81#issuecomment-1787039792) using ```True```?

**Comment by sancarn** [comment]
So let me get this straight... There isn't actually a problem with 

```vb
#If VBA7 Then
#Else
   Public Enum LongPtr:[_]:End Enum
#End If
```

? 😂😂

**Comment by KallunWillock** [comment]
Is it possible that OP has added a 32bit type library reference to the project that is conflicting with this enum declaration? Eg: https://www.vbforums.com/showthread.php?898078-Typelib-to-add-LongPtr-type-to-VB6-for-universal-codebases
