### ISSUE TITLE
stdHTTP - bug using proxy only for stdHTTP

### ISSUE THREAD

**Issue by 6DiegoDiego9** [sancarn/stdVBA#87]
I manually set stdHTTP to use a proxy, with the following instructions:
options("ProxyServer") = proxyString '(ip:port)
options("ProxyUser") = username
options("ProxyPass") = password

and I don't use a proxy outside stdHTTP (no proxy for browser).

However:
A) if I set options("AutoProxy") = False, the proxy is simply not used at all by stdHTTP
B) if I set options("AutoProxy") = True, protInit calls LoadAutoProxy, that calls GetProxyCurrentUser, that eventually calls WinHttpGetProxyForUrl which fails with Err.LastDllError = ERROR_WINHTTP_AUTODETECTION_FAILED (12180)   (maybe because I don't use a proxy except for stdHTTP?)

**Comment by sancarn** [comment]
Thanks for reporting the issue! You're right, I don't set proxy information unless it's coming from the autoproxy! 

I'll need to add:

```vb
If options.exists("ProxyServer") then request.SetProxy ProxySetting.Proxy, info.ProxyServer, info.ProxyBypass
If options.exists("ProxyUser") then request.SetCredentials options("ProxyUser"), options("ProxyPass"), SetCredentialsType.ForProxy
```
to `protInit`

**Comment by sancarn** [comment]
Think this should be completed now :) Let me know if it works or not.

**Comment by sancarn** [comment]
Hi there, in the works for building the feature up again. But to fix this we'll be moving away from an explicit `AutoProxy` param in `CreateOptions()` and instead moving to a `ProxyInfo` param instead. `ProxyInfo` can be created from `CreateProxy()`

```vb
stdHTTP.Create(sURL, options:=stdHTTP.CreateOptions(Proxy:= stdHTTP.CreateProxy(ProxyTypeManual, myServer, myBypass, myUser, myPass))
```

**Comment by sancarn** [comment]
Hi @6DiegoDiego9, I've just pushed a fix.

**Comment by 6DiegoDiego9** [comment]
No more compile error, however I'm totally new to stdHTTP. Could you please write an "hello world" example using proxy with username/password?

**Comment by sancarn** [comment]
Are you sure you want a proxy?

It's hard to give you an example without first having a proxy to use, which is why this feature hasn't really been tested. Personally I always get by with what autoproxy is giving... As far as I know:

```vb
const sURL as string = "http://google.com"
const ProxyServer as string = "http://myproxy.whatever:port"
const ProxyUser as string = "MyUsername"
const ProxyPass as string = "MyPassword"
Dim resp as stdHTTP
set resp = stdHTTP.Create(sURL, options:=stdHTTP.CreateOptions(Proxy:= stdHTTP.CreateProxy(ProxyTypeManual, ProxyServer, "", ProxyUser, ProxyPass))
```

should work... Unless you don't actually want a proxy, and are looking for something else.

**Comment by 6DiegoDiego9** [comment]
Thanks, it worked!

ProxyServer can also be simply "IP:port"
