### ISSUE TITLE
stdTimer sheet reference

### ISSUE THREAD

**Issue by yipinghuang1991** [sancarn/stdVBA#89]
[In stdTimer](https://github.com/sancarn/stdVBA/blob/master/src/stdTimer.cls)
Line 153
Would you please change `Sheet1` to `Sheets(1)`?
Because `Sheet1`, `Sheet2`, `Sheet3`, ... , etc is not the default naming scheme in my locale.
It's `工作表1`, `工作表2`, `工作表3`, ... , instead.

**Comment by sancarn** [comment]
Wow, kinda shocked microsoft did that... But ok, good to know :)
