### ISSUE TITLE
stdProcess does not parse, property closed with End Function

### ISSUE THREAD

**Issue by Beakerboy** [sancarn/stdVBA#91]
Two method signatures are incorrect. They begin with ‘Public Property’ but close with ‘End Function’.
```
Returns whether the process is still running or not
'@returns - `true` if the process is still running, `false` otherwise
Public Property Get isRunning() As Boolean
  isRunning = GetProcessVersion(pProcessId) > 0
End Function

'Returns whether the process is critical or not
'@returns - `true` if the process is critical, `false` otherwise
Public Property Get isCritical() As Boolean
  'Note: IsProcessCritical can return a weird boolean where `bool` and `Not bool` both result in `True`, which is nonsense...
  'for this reason we explicitely cast to a long here...
  If CLng(IsProcessCritical(pQueryInfoHandle, isCritical)) = 0 Then
    Err.Raise 1, "stdProcess.isCritical", "Cannot get critical status of process. Error code 0x" & Hex(Err.LastDllError)
  End If
End Function
```

**Comment by sancarn** [comment]
Very true, thanks a bunch for the report!

**Comment by Beakerboy** [comment]
I also see in stdArray that every line continuation symbol has a space after it. Did you manually type those? The VBA IDE will automatically strip them off, and according to Microsoft, a "Line continuation element" must be a space and an underscore that is immediately followed by a line-break.

**Comment by sancarn** [comment]
> Did you manually type those?

I did, I think in the VBE it used to not recognise the line break unless there was a leading space? Either that or something to do with VSCode highlighter perhaps... Can't totally remember it now, because I kinda just do it automatically... 😅

**Comment by Beakerboy** [comment]
BTW, here's the script I'm using to test my ANTLR grammar:
https://github.com/Beakerboy/stdVBA/blob/dev/.github/workflows/lint_vba.yml

Your libraries do enough complicated stuff that I'm finding a ton of bugs in the written VBA language specification document.

**Comment by sancarn** [comment]
Amazing! Interesting that you can't do a PR with that...

**Comment by sancarn** [comment]
@Beakerboy  Do you know if there is a way of finding the issues you have logged and tracking progress?

**Comment by Beakerboy** [comment]
Yeah, the open specifications team has been great about letting me know that what I’m saying is actually correct, and that the document will have the appropriate changes in the next release.

I have a list of the issues:
https://github.com/Beakerboy/grammars-v4/tree/coverage/vba/vba7_1

**Comment by Beakerboy** [comment]
StdPerformance line 208 has the same problem.

**Comment by sancarn** [comment]
So it does! Thanks!

**Comment by Beakerboy** [comment]
The precompiler, grammar, and linter are all very much alpha-beta. I’m using your repo to find and fix bugs so no need to file issue unless you wanted to supply a pull request. However, I’ll run through the few errors your projects are showing so you know what’s what.

first off, I delete all your code in WIP. Several files have comments before the CLASS or Attribute header, which immediately causes parsing errors. Feel free to clean some of it up if you want me to test it.
 
 the VBAL document does not address member attributes in Redim statements, so 
```
‘ Full member addressing does not work
Redim this.foo(1 To 2)

‘ Also in a with block
With Foo
    Redim .bar(1 To 2)
End With
```

The precompiler is doing something weird in stdClipboard. It’s failing to comment out a line that should be commented. It’s either a grammar issue in vba_cc.g4 or something in vba_precompiler. I see some commented lines in the code are not getting another single-quote added to them, so I suspect comment lines are affecting the calculation of the line number.

The weird string In string builder tests is not paring correctly. I need to use lab.antlr.org to work through that.

I need to add VB_VarHelpId to the list of available statements at the module level.

**Comment by sancarn** [comment]
> first off, I delete all your code in WIP

Tbh I would suggest that anyway. That whole folder is a mess of incomplete ideas. I really should clean it up fully...

**Comment by Beakerboy** [comment]
My rule of thumb is my main or master branch is all ready for prime-time. My dev branch is all valid, but not documented or does not 100% coverage, and then a have feature branches for works in progress.

**Comment by Beakerboy** [comment]
All the outstanding issues with the parsing stage of the Linting tool have been resolved, and it didn’t find any more issues with tour code. If you want to mess around with the linter, change parse-only to dev to see the list of recommended whitespace, capitalization and documentation changes…and please let me know if there are any you would like added.

**Comment by sancarn** [comment]
Not sure I gully agree with some of the linter's whitespace complaints e.g.

![image](https://github.com/sancarn/stdVBA/assets/7938900/f18688b6-a927-4a06-a22f-54c2bcdc9a6e)

My assumption is these will only be warnings, but still most linters that I know of are whitespace agnostic and case insensitive... Maybe this makes sense for an IDE addin though... I'm not fully sure.  I've seen no errors about comments/docs at the moment which I think is fair. certainly something that would be a nice warning though - e.g. undocumented parameters of a function etc.

**Comment by Beakerboy** [comment]
The plan is to allow the whitespace settings to be configurable, or make it easy enough for someone to drop in their own rule. The big one I see in your code is inconsistent capitalization of keywords. 

Parsing is a “must”, while the Linting side is very much style, like, do I use the Call keyword or not; do I force the use of Public before the function name. In your case, you want to align comments which is a different style then I have code for, and the reason I’m interested in looking at your code is to see what style differences I should develop checks for.

**Comment by sancarn** [comment]
Totally agree with everything you're saying.

Your plan to check for a leading comment sounds good enough to me ☺️

**Comment by Beakerboy** [comment]
The plan is to have the “severity” of each rule configurable. Parsing problems would be a “Failure”, anything that the Excel VBA IDE would not allow would be an “error”. Stuff like indentation would be a “warning” and then other stuff like documentation would be a “Notice”. Planning on allowing “Deprecation” as well.

**Comment by sancarn** [comment]
I think most things like keywords not being capitalised would be something i'd be happy to automate away. Expect this is a long term goal?
