### ISSUE TITLE
stdJSON issues + improvement suggestions

### ISSUE THREAD

**Issue by thefasquelle** [sancarn/stdVBA#93]
Hello,
looking for a JSON module to handle JSON config files, I tested your stdJSON class. The first thing i did was trying the example at the top of the file, with just one additional line to write to a file. It didn't work, so I digged into the code and added Option Explicit. Then VBE and rubberduck pointed the following issues :
- In ToFile():
```VBA
Public Sub ToFile(ByVal sPath As String, Optional ByVal prettyIndent As Long = 0)
    Dim ff As Long: ff = FreeFile
    Open sPath For Output As #ff
    Print #ff, Data
    Close #ff
End Sub
```
Data is not defined. With Option Explicit it will fail at runtime. Without Option Explicit, it juste saves an empty file. I replaced it with `Print #ff, Me.ToString(prettyIndent <> 0, prettyIndent)`

- In simpleStringify():
```VBA
Case vbInteger, vbDouble, vbFloat
```
vbFloat is undefined, I guess you meant vbSingle ?
There is no impact at runtime because the Case Else code works for Singles ... except if the computer locale does not use a dot for the decimal separator. So I suggest you replace this:
```VBA
Case vbInteger, vbDouble, vbFloat
      simpleStringify = value
```
with this
```VBA
    Case vbInteger
      simpleStringify = CStr(value)
    Case vbDouble, vbSingle
      Dim DecimalSeparator As String: DecimalSeparator = Format(0, ".") ' Actually do this once in Class_Initalize
      simpleStringify = Replace(CStr(value), DecimalSeparator, ".")
```

Also the example snippet is not functional because of the .obj and .toVBON() methods are not implemented (I suppose toVBON is actually ToVBObject ?)

And lastly, the pretty indent function seems broken, here is the result I got from the example snippet:
```JSON
{
  "key":  {
    "a":1,
    "b":"hello",
    "val":        [
                                                [
                                                1,
                                                "hello",
                                                "shit"
                                    ]

        ]

  }

}

```

This leave me wondering: is it safe for me to use this class ? Has it been thoroughly tested ? The ToFile() method at least has not.
I wanted to use this class because its API is pretty nice and the code is not too big but these issues show a lack of testing.

**Comment by sancarn** [comment]
Hi there,

Thanks for logging the issues. This is something I had ran into too, but had totally forgot about. These issues are now fixed in the latest release.

> This leave me wondering: is it safe for me to use this class? Has it been thoroughly tested?

Depends what you mean. We've been using this in one of our business projects, but the reality is we have only thoroughly tested the things we use regularly - parsing, creation and non-pretty stringification - which are really the only 2 things which matter also. Pretty printing was always added as a nice-to-have for debugging purposes.
