### ISSUE TITLE
Missing variable declarations

### ISSUE THREAD

**Issue by 6DiegoDiego9** [sancarn/stdVBA#95]
I use to add "Option Explicit" to every module (module/cls/frm), and after I added it to stdHTTP I spotted this:

![image](https://github.com/sancarn/stdVBA/assets/109476941/6bb29a80-760d-44db-8900-8a35ad903e33)

Not sure if you intended to:
a) leave them empty, as it currently does (without Option Explicit)
b) pass them as arguments
c) add them into the "info" Type (info.User and info.Pass)

**Comment by sancarn** [comment]
For now I've set them to `Empty` - not sure they are required at all, but for now at least I've managed to use the class with them `Empty` anyway. It's possible that my intention was to allow them to be passed as arguments somehow... not sure.
